[package]
name = "cyclic-scheduler"
version = "0.1.0"
edition = "2021"

[lib]
name = "cyclic_scheduler"
crate-type = ["cdylib", "lib"]

[dependencies]
grb = "2.*"
itertools = "0.13.*"
mdsdf = { path = "../mdsdf" }
buffer_sizing = { path = "../buffer_sizing" }
milp_formulation = { path = "../milp_formulation" }

[dependencies.pyo3]
version = "0.21.*"
features = ["extension-module"]

[build-dependencies]
npm_rs = "1.*"
