[package]
name = "sdf3_xml_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
grb = "2.*"
serde-xml-rs = "0.6.*"
mdsdf = { path = "../mdsdf" }
milp_formulation = { path = "../milp_formulation" }
buffer_sizing = { path = "../buffer_sizing" }
serde = { version = "1.*", features = ["derive"] }
