[project]
name = "stream_cyclic_scheduler"
version = "0.1.0"
description = ""
authors = [{ name="Andrea Nardi", email="buongiorno19972@gmail.com"}]

dependencies = [
    "networkx >= 3",
    "stream-dse @ git+https://github.com/KULeuven-MICAS/stream.git",
    "notebook >= 7",
    "matplotlib == 3.6",
    "plotly",
    "pandas",
    "cerberus"
]